/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PartnerReferralRouteImport } from './routes/partner-referral'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffWorkRouteImport } from './routes/staff.work'
import { Route as StaffVusiToolsRouteImport } from './routes/staff.vusi-tools'
import { Route as StaffVusiRouteImport } from './routes/staff.vusi'
import { Route as StaffVoiceRouteImport } from './routes/staff.voice'
import { Route as StaffSubcontractorsRouteImport } from './routes/staff.subcontractors'
import { Route as StaffSteveRouteImport } from './routes/staff.steve'
import { Route as StaffSiteVisitsRouteImport } from './routes/staff.site-visits'
import { Route as StaffSettingsRouteImport } from './routes/staff.settings'
import { Route as StaffScheduleRouteImport } from './routes/staff.schedule'
import { Route as StaffReportsRouteImport } from './routes/staff.reports'
import { Route as StaffQuotesRouteImport } from './routes/staff.quotes'
import { Route as StaffQuotationsRouteImport } from './routes/staff.quotations'
import { Route as StaffProjectsRouteImport } from './routes/staff.projects'
import { Route as StaffProjectStickerRouteImport } from './routes/staff.project-sticker'
import { Route as StaffProjectQrRouteImport } from './routes/staff.project-qr'
import { Route as StaffPoOrdersRouteImport } from './routes/staff.po-orders'
import { Route as StaffLoginRouteImport } from './routes/staff.login'
import { Route as StaffInspectionsRouteImport } from './routes/staff.inspections'
import { Route as StaffInspectionReportsRouteImport } from './routes/staff.inspection-reports'
import { Route as StaffHelpRouteImport } from './routes/staff.help'
import { Route as StaffGrowthRouteImport } from './routes/staff.growth'
import { Route as StaffFieldWorkRouteImport } from './routes/staff.field-work'
import { Route as StaffEmailRouteImport } from './routes/staff.email'
import { Route as StaffDocsRouteImport } from './routes/staff.docs'
import { Route as StaffCrmRouteImport } from './routes/staff.crm'
import { Route as StaffConsultingReportsRouteImport } from './routes/staff.consulting-reports'
import { Route as StaffComplianceRouteImport } from './routes/staff.compliance'
import { Route as StaffClientsRouteImport } from './routes/staff.clients'
import { Route as StaffChatRouteImport } from './routes/staff.chat'
import { Route as StaffCapabilityRouteImport } from './routes/staff.capability'
import { Route as StaffBillingRouteImport } from './routes/staff.billing'
import { Route as StaffAutomationsRouteImport } from './routes/staff.automations'
import { Route as StaffAssetsRiskRouteImport } from './routes/staff.assets-risk'
import { Route as SignTokenRouteImport } from './routes/sign.$token'
import { Route as ProjectScanTokenRouteImport } from './routes/project-scan.$token'
import { Route as StaffVusiToolsFindingsReportRouteImport } from './routes/staff.vusi-tools.findings-report'
import { Route as StaffQuotesOnsiteRouteImport } from './routes/staff.quotes.onsite'
import { Route as StaffQuotesNewRouteImport } from './routes/staff.quotes.new'
import { Route as StaffQuotesQuoteIdRouteImport } from './routes/staff.quotes.$quoteId'
import { Route as StaffGrowthSegmentsRouteImport } from './routes/staff.growth.segments'
import { Route as StaffGrowthCampaignsRouteImport } from './routes/staff.growth.campaigns'
import { Route as StaffCrmContactsRouteImport } from './routes/staff.crm.contacts'
import { Route as StaffGrowthCampaignsCampaignIdRouteImport } from './routes/staff.growth.campaigns.$campaignId'
import { Route as StaffCrmDealsDealIdRouteImport } from './routes/staff.crm.deals.$dealId'
import { Route as StaffCrmContactsContactIdRouteImport } from './routes/staff.crm.contacts.$contactId'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerReferralRoute = PartnerReferralRouteImport.update({
  id: '/partner-referral',
  path: '/partner-referral',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffWorkRoute = StaffWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => StaffRoute,
} as any)
const StaffVusiToolsRoute = StaffVusiToolsRouteImport.update({
  id: '/vusi-tools',
  path: '/vusi-tools',
  getParentRoute: () => StaffRoute,
} as any)
const StaffVusiRoute = StaffVusiRouteImport.update({
  id: '/vusi',
  path: '/vusi',
  getParentRoute: () => StaffRoute,
} as any)
const StaffVoiceRoute = StaffVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => StaffRoute,
} as any)
const StaffSubcontractorsRoute = StaffSubcontractorsRouteImport.update({
  id: '/subcontractors',
  path: '/subcontractors',
  getParentRoute: () => StaffRoute,
} as any)
const StaffSteveRoute = StaffSteveRouteImport.update({
  id: '/steve',
  path: '/steve',
  getParentRoute: () => StaffRoute,
} as any)
const StaffSiteVisitsRoute = StaffSiteVisitsRouteImport.update({
  id: '/site-visits',
  path: '/site-visits',
  getParentRoute: () => StaffRoute,
} as any)
const StaffSettingsRoute = StaffSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StaffRoute,
} as any)
const StaffScheduleRoute = StaffScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => StaffRoute,
} as any)
const StaffReportsRoute = StaffReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => StaffRoute,
} as any)
const StaffQuotesRoute = StaffQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => StaffRoute,
} as any)
const StaffQuotationsRoute = StaffQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => StaffRoute,
} as any)
const StaffProjectsRoute = StaffProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => StaffRoute,
} as any)
const StaffProjectStickerRoute = StaffProjectStickerRouteImport.update({
  id: '/project-sticker',
  path: '/project-sticker',
  getParentRoute: () => StaffRoute,
} as any)
const StaffProjectQrRoute = StaffProjectQrRouteImport.update({
  id: '/project-qr',
  path: '/project-qr',
  getParentRoute: () => StaffRoute,
} as any)
const StaffPoOrdersRoute = StaffPoOrdersRouteImport.update({
  id: '/po-orders',
  path: '/po-orders',
  getParentRoute: () => StaffRoute,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => StaffRoute,
} as any)
const StaffInspectionsRoute = StaffInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => StaffRoute,
} as any)
const StaffInspectionReportsRoute = StaffInspectionReportsRouteImport.update({
  id: '/inspection-reports',
  path: '/inspection-reports',
  getParentRoute: () => StaffRoute,
} as any)
const StaffHelpRoute = StaffHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => StaffRoute,
} as any)
const StaffGrowthRoute = StaffGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => StaffRoute,
} as any)
const StaffFieldWorkRoute = StaffFieldWorkRouteImport.update({
  id: '/field-work',
  path: '/field-work',
  getParentRoute: () => StaffRoute,
} as any)
const StaffEmailRoute = StaffEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => StaffRoute,
} as any)
const StaffDocsRoute = StaffDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCrmRoute = StaffCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => StaffRoute,
} as any)
const StaffConsultingReportsRoute = StaffConsultingReportsRouteImport.update({
  id: '/consulting-reports',
  path: '/consulting-reports',
  getParentRoute: () => StaffRoute,
} as any)
const StaffComplianceRoute = StaffComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => StaffRoute,
} as any)
const StaffClientsRoute = StaffClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => StaffRoute,
} as any)
const StaffChatRoute = StaffChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCapabilityRoute = StaffCapabilityRouteImport.update({
  id: '/capability',
  path: '/capability',
  getParentRoute: () => StaffRoute,
} as any)
const StaffBillingRoute = StaffBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAutomationsRoute = StaffAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAssetsRiskRoute = StaffAssetsRiskRouteImport.update({
  id: '/assets-risk',
  path: '/assets-risk',
  getParentRoute: () => StaffRoute,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectScanTokenRoute = ProjectScanTokenRouteImport.update({
  id: '/project-scan/$token',
  path: '/project-scan/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffVusiToolsFindingsReportRoute =
  StaffVusiToolsFindingsReportRouteImport.update({
    id: '/findings-report',
    path: '/findings-report',
    getParentRoute: () => StaffVusiToolsRoute,
  } as any)
const StaffQuotesOnsiteRoute = StaffQuotesOnsiteRouteImport.update({
  id: '/onsite',
  path: '/onsite',
  getParentRoute: () => StaffQuotesRoute,
} as any)
const StaffQuotesNewRoute = StaffQuotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StaffQuotesRoute,
} as any)
const StaffQuotesQuoteIdRoute = StaffQuotesQuoteIdRouteImport.update({
  id: '/$quoteId',
  path: '/$quoteId',
  getParentRoute: () => StaffQuotesRoute,
} as any)
const StaffGrowthSegmentsRoute = StaffGrowthSegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => StaffGrowthRoute,
} as any)
const StaffGrowthCampaignsRoute = StaffGrowthCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => StaffGrowthRoute,
} as any)
const StaffCrmContactsRoute = StaffCrmContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => StaffCrmRoute,
} as any)
const StaffGrowthCampaignsCampaignIdRoute =
  StaffGrowthCampaignsCampaignIdRouteImport.update({
    id: '/$campaignId',
    path: '/$campaignId',
    getParentRoute: () => StaffGrowthCampaignsRoute,
  } as any)
const StaffCrmDealsDealIdRoute = StaffCrmDealsDealIdRouteImport.update({
  id: '/deals/$dealId',
  path: '/deals/$dealId',
  getParentRoute: () => StaffCrmRoute,
} as any)
const StaffCrmContactsContactIdRoute =
  StaffCrmContactsContactIdRouteImport.update({
    id: '/$contactId',
    path: '/$contactId',
    getParentRoute: () => StaffCrmContactsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/partner-referral': typeof PartnerReferralRoute
  '/services': typeof ServicesRoute
  '/staff': typeof StaffRouteWithChildren
  '/project-scan/$token': typeof ProjectScanTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/staff/assets-risk': typeof StaffAssetsRiskRoute
  '/staff/automations': typeof StaffAutomationsRoute
  '/staff/billing': typeof StaffBillingRoute
  '/staff/capability': typeof StaffCapabilityRoute
  '/staff/chat': typeof StaffChatRoute
  '/staff/clients': typeof StaffClientsRoute
  '/staff/compliance': typeof StaffComplianceRoute
  '/staff/consulting-reports': typeof StaffConsultingReportsRoute
  '/staff/crm': typeof StaffCrmRouteWithChildren
  '/staff/docs': typeof StaffDocsRoute
  '/staff/email': typeof StaffEmailRoute
  '/staff/field-work': typeof StaffFieldWorkRoute
  '/staff/growth': typeof StaffGrowthRouteWithChildren
  '/staff/help': typeof StaffHelpRoute
  '/staff/inspection-reports': typeof StaffInspectionReportsRoute
  '/staff/inspections': typeof StaffInspectionsRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/po-orders': typeof StaffPoOrdersRoute
  '/staff/project-qr': typeof StaffProjectQrRoute
  '/staff/project-sticker': typeof StaffProjectStickerRoute
  '/staff/projects': typeof StaffProjectsRoute
  '/staff/quotations': typeof StaffQuotationsRoute
  '/staff/quotes': typeof StaffQuotesRouteWithChildren
  '/staff/reports': typeof StaffReportsRoute
  '/staff/schedule': typeof StaffScheduleRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/staff/site-visits': typeof StaffSiteVisitsRoute
  '/staff/steve': typeof StaffSteveRoute
  '/staff/subcontractors': typeof StaffSubcontractorsRoute
  '/staff/voice': typeof StaffVoiceRoute
  '/staff/vusi': typeof StaffVusiRoute
  '/staff/vusi-tools': typeof StaffVusiToolsRouteWithChildren
  '/staff/work': typeof StaffWorkRoute
  '/staff/': typeof StaffIndexRoute
  '/staff/crm/contacts': typeof StaffCrmContactsRouteWithChildren
  '/staff/growth/campaigns': typeof StaffGrowthCampaignsRouteWithChildren
  '/staff/growth/segments': typeof StaffGrowthSegmentsRoute
  '/staff/quotes/$quoteId': typeof StaffQuotesQuoteIdRoute
  '/staff/quotes/new': typeof StaffQuotesNewRoute
  '/staff/quotes/onsite': typeof StaffQuotesOnsiteRoute
  '/staff/vusi-tools/findings-report': typeof StaffVusiToolsFindingsReportRoute
  '/staff/crm/contacts/$contactId': typeof StaffCrmContactsContactIdRoute
  '/staff/crm/deals/$dealId': typeof StaffCrmDealsDealIdRoute
  '/staff/growth/campaigns/$campaignId': typeof StaffGrowthCampaignsCampaignIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/partner-referral': typeof PartnerReferralRoute
  '/services': typeof ServicesRoute
  '/project-scan/$token': typeof ProjectScanTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/staff/assets-risk': typeof StaffAssetsRiskRoute
  '/staff/automations': typeof StaffAutomationsRoute
  '/staff/billing': typeof StaffBillingRoute
  '/staff/capability': typeof StaffCapabilityRoute
  '/staff/chat': typeof StaffChatRoute
  '/staff/clients': typeof StaffClientsRoute
  '/staff/compliance': typeof StaffComplianceRoute
  '/staff/consulting-reports': typeof StaffConsultingReportsRoute
  '/staff/crm': typeof StaffCrmRouteWithChildren
  '/staff/docs': typeof StaffDocsRoute
  '/staff/email': typeof StaffEmailRoute
  '/staff/field-work': typeof StaffFieldWorkRoute
  '/staff/growth': typeof StaffGrowthRouteWithChildren
  '/staff/help': typeof StaffHelpRoute
  '/staff/inspection-reports': typeof StaffInspectionReportsRoute
  '/staff/inspections': typeof StaffInspectionsRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/po-orders': typeof StaffPoOrdersRoute
  '/staff/project-qr': typeof StaffProjectQrRoute
  '/staff/project-sticker': typeof StaffProjectStickerRoute
  '/staff/projects': typeof StaffProjectsRoute
  '/staff/quotations': typeof StaffQuotationsRoute
  '/staff/quotes': typeof StaffQuotesRouteWithChildren
  '/staff/reports': typeof StaffReportsRoute
  '/staff/schedule': typeof StaffScheduleRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/staff/site-visits': typeof StaffSiteVisitsRoute
  '/staff/steve': typeof StaffSteveRoute
  '/staff/subcontractors': typeof StaffSubcontractorsRoute
  '/staff/voice': typeof StaffVoiceRoute
  '/staff/vusi': typeof StaffVusiRoute
  '/staff/vusi-tools': typeof StaffVusiToolsRouteWithChildren
  '/staff/work': typeof StaffWorkRoute
  '/staff': typeof StaffIndexRoute
  '/staff/crm/contacts': typeof StaffCrmContactsRouteWithChildren
  '/staff/growth/campaigns': typeof StaffGrowthCampaignsRouteWithChildren
  '/staff/growth/segments': typeof StaffGrowthSegmentsRoute
  '/staff/quotes/$quoteId': typeof StaffQuotesQuoteIdRoute
  '/staff/quotes/new': typeof StaffQuotesNewRoute
  '/staff/quotes/onsite': typeof StaffQuotesOnsiteRoute
  '/staff/vusi-tools/findings-report': typeof StaffVusiToolsFindingsReportRoute
  '/staff/crm/contacts/$contactId': typeof StaffCrmContactsContactIdRoute
  '/staff/crm/deals/$dealId': typeof StaffCrmDealsDealIdRoute
  '/staff/growth/campaigns/$campaignId': typeof StaffGrowthCampaignsCampaignIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/partner-referral': typeof PartnerReferralRoute
  '/services': typeof ServicesRoute
  '/staff': typeof StaffRouteWithChildren
  '/project-scan/$token': typeof ProjectScanTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/staff/assets-risk': typeof StaffAssetsRiskRoute
  '/staff/automations': typeof StaffAutomationsRoute
  '/staff/billing': typeof StaffBillingRoute
  '/staff/capability': typeof StaffCapabilityRoute
  '/staff/chat': typeof StaffChatRoute
  '/staff/clients': typeof StaffClientsRoute
  '/staff/compliance': typeof StaffComplianceRoute
  '/staff/consulting-reports': typeof StaffConsultingReportsRoute
  '/staff/crm': typeof StaffCrmRouteWithChildren
  '/staff/docs': typeof StaffDocsRoute
  '/staff/email': typeof StaffEmailRoute
  '/staff/field-work': typeof StaffFieldWorkRoute
  '/staff/growth': typeof StaffGrowthRouteWithChildren
  '/staff/help': typeof StaffHelpRoute
  '/staff/inspection-reports': typeof StaffInspectionReportsRoute
  '/staff/inspections': typeof StaffInspectionsRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/po-orders': typeof StaffPoOrdersRoute
  '/staff/project-qr': typeof StaffProjectQrRoute
  '/staff/project-sticker': typeof StaffProjectStickerRoute
  '/staff/projects': typeof StaffProjectsRoute
  '/staff/quotations': typeof StaffQuotationsRoute
  '/staff/quotes': typeof StaffQuotesRouteWithChildren
  '/staff/reports': typeof StaffReportsRoute
  '/staff/schedule': typeof StaffScheduleRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/staff/site-visits': typeof StaffSiteVisitsRoute
  '/staff/steve': typeof StaffSteveRoute
  '/staff/subcontractors': typeof StaffSubcontractorsRoute
  '/staff/voice': typeof StaffVoiceRoute
  '/staff/vusi': typeof StaffVusiRoute
  '/staff/vusi-tools': typeof StaffVusiToolsRouteWithChildren
  '/staff/work': typeof StaffWorkRoute
  '/staff/': typeof StaffIndexRoute
  '/staff/crm/contacts': typeof StaffCrmContactsRouteWithChildren
  '/staff/growth/campaigns': typeof StaffGrowthCampaignsRouteWithChildren
  '/staff/growth/segments': typeof StaffGrowthSegmentsRoute
  '/staff/quotes/$quoteId': typeof StaffQuotesQuoteIdRoute
  '/staff/quotes/new': typeof StaffQuotesNewRoute
  '/staff/quotes/onsite': typeof StaffQuotesOnsiteRoute
  '/staff/vusi-tools/findings-report': typeof StaffVusiToolsFindingsReportRoute
  '/staff/crm/contacts/$contactId': typeof StaffCrmContactsContactIdRoute
  '/staff/crm/deals/$dealId': typeof StaffCrmDealsDealIdRoute
  '/staff/growth/campaigns/$campaignId': typeof StaffGrowthCampaignsCampaignIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/partner-referral'
    | '/services'
    | '/staff'
    | '/project-scan/$token'
    | '/sign/$token'
    | '/staff/assets-risk'
    | '/staff/automations'
    | '/staff/billing'
    | '/staff/capability'
    | '/staff/chat'
    | '/staff/clients'
    | '/staff/compliance'
    | '/staff/consulting-reports'
    | '/staff/crm'
    | '/staff/docs'
    | '/staff/email'
    | '/staff/field-work'
    | '/staff/growth'
    | '/staff/help'
    | '/staff/inspection-reports'
    | '/staff/inspections'
    | '/staff/login'
    | '/staff/po-orders'
    | '/staff/project-qr'
    | '/staff/project-sticker'
    | '/staff/projects'
    | '/staff/quotations'
    | '/staff/quotes'
    | '/staff/reports'
    | '/staff/schedule'
    | '/staff/settings'
    | '/staff/site-visits'
    | '/staff/steve'
    | '/staff/subcontractors'
    | '/staff/voice'
    | '/staff/vusi'
    | '/staff/vusi-tools'
    | '/staff/work'
    | '/staff/'
    | '/staff/crm/contacts'
    | '/staff/growth/campaigns'
    | '/staff/growth/segments'
    | '/staff/quotes/$quoteId'
    | '/staff/quotes/new'
    | '/staff/quotes/onsite'
    | '/staff/vusi-tools/findings-report'
    | '/staff/crm/contacts/$contactId'
    | '/staff/crm/deals/$dealId'
    | '/staff/growth/campaigns/$campaignId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/partner-referral'
    | '/services'
    | '/project-scan/$token'
    | '/sign/$token'
    | '/staff/assets-risk'
    | '/staff/automations'
    | '/staff/billing'
    | '/staff/capability'
    | '/staff/chat'
    | '/staff/clients'
    | '/staff/compliance'
    | '/staff/consulting-reports'
    | '/staff/crm'
    | '/staff/docs'
    | '/staff/email'
    | '/staff/field-work'
    | '/staff/growth'
    | '/staff/help'
    | '/staff/inspection-reports'
    | '/staff/inspections'
    | '/staff/login'
    | '/staff/po-orders'
    | '/staff/project-qr'
    | '/staff/project-sticker'
    | '/staff/projects'
    | '/staff/quotations'
    | '/staff/quotes'
    | '/staff/reports'
    | '/staff/schedule'
    | '/staff/settings'
    | '/staff/site-visits'
    | '/staff/steve'
    | '/staff/subcontractors'
    | '/staff/voice'
    | '/staff/vusi'
    | '/staff/vusi-tools'
    | '/staff/work'
    | '/staff'
    | '/staff/crm/contacts'
    | '/staff/growth/campaigns'
    | '/staff/growth/segments'
    | '/staff/quotes/$quoteId'
    | '/staff/quotes/new'
    | '/staff/quotes/onsite'
    | '/staff/vusi-tools/findings-report'
    | '/staff/crm/contacts/$contactId'
    | '/staff/crm/deals/$dealId'
    | '/staff/growth/campaigns/$campaignId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/partner-referral'
    | '/services'
    | '/staff'
    | '/project-scan/$token'
    | '/sign/$token'
    | '/staff/assets-risk'
    | '/staff/automations'
    | '/staff/billing'
    | '/staff/capability'
    | '/staff/chat'
    | '/staff/clients'
    | '/staff/compliance'
    | '/staff/consulting-reports'
    | '/staff/crm'
    | '/staff/docs'
    | '/staff/email'
    | '/staff/field-work'
    | '/staff/growth'
    | '/staff/help'
    | '/staff/inspection-reports'
    | '/staff/inspections'
    | '/staff/login'
    | '/staff/po-orders'
    | '/staff/project-qr'
    | '/staff/project-sticker'
    | '/staff/projects'
    | '/staff/quotations'
    | '/staff/quotes'
    | '/staff/reports'
    | '/staff/schedule'
    | '/staff/settings'
    | '/staff/site-visits'
    | '/staff/steve'
    | '/staff/subcontractors'
    | '/staff/voice'
    | '/staff/vusi'
    | '/staff/vusi-tools'
    | '/staff/work'
    | '/staff/'
    | '/staff/crm/contacts'
    | '/staff/growth/campaigns'
    | '/staff/growth/segments'
    | '/staff/quotes/$quoteId'
    | '/staff/quotes/new'
    | '/staff/quotes/onsite'
    | '/staff/vusi-tools/findings-report'
    | '/staff/crm/contacts/$contactId'
    | '/staff/crm/deals/$dealId'
    | '/staff/growth/campaigns/$campaignId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  PartnerReferralRoute: typeof PartnerReferralRoute
  ServicesRoute: typeof ServicesRoute
  StaffRoute: typeof StaffRouteWithChildren
  ProjectScanTokenRoute: typeof ProjectScanTokenRoute
  SignTokenRoute: typeof SignTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-referral': {
      id: '/partner-referral'
      path: '/partner-referral'
      fullPath: '/partner-referral'
      preLoaderRoute: typeof PartnerReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/work': {
      id: '/staff/work'
      path: '/work'
      fullPath: '/staff/work'
      preLoaderRoute: typeof StaffWorkRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/vusi-tools': {
      id: '/staff/vusi-tools'
      path: '/vusi-tools'
      fullPath: '/staff/vusi-tools'
      preLoaderRoute: typeof StaffVusiToolsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/vusi': {
      id: '/staff/vusi'
      path: '/vusi'
      fullPath: '/staff/vusi'
      preLoaderRoute: typeof StaffVusiRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/voice': {
      id: '/staff/voice'
      path: '/voice'
      fullPath: '/staff/voice'
      preLoaderRoute: typeof StaffVoiceRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/subcontractors': {
      id: '/staff/subcontractors'
      path: '/subcontractors'
      fullPath: '/staff/subcontractors'
      preLoaderRoute: typeof StaffSubcontractorsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/steve': {
      id: '/staff/steve'
      path: '/steve'
      fullPath: '/staff/steve'
      preLoaderRoute: typeof StaffSteveRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/site-visits': {
      id: '/staff/site-visits'
      path: '/site-visits'
      fullPath: '/staff/site-visits'
      preLoaderRoute: typeof StaffSiteVisitsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/settings': {
      id: '/staff/settings'
      path: '/settings'
      fullPath: '/staff/settings'
      preLoaderRoute: typeof StaffSettingsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/schedule': {
      id: '/staff/schedule'
      path: '/schedule'
      fullPath: '/staff/schedule'
      preLoaderRoute: typeof StaffScheduleRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/reports': {
      id: '/staff/reports'
      path: '/reports'
      fullPath: '/staff/reports'
      preLoaderRoute: typeof StaffReportsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/quotes': {
      id: '/staff/quotes'
      path: '/quotes'
      fullPath: '/staff/quotes'
      preLoaderRoute: typeof StaffQuotesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/quotations': {
      id: '/staff/quotations'
      path: '/quotations'
      fullPath: '/staff/quotations'
      preLoaderRoute: typeof StaffQuotationsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/projects': {
      id: '/staff/projects'
      path: '/projects'
      fullPath: '/staff/projects'
      preLoaderRoute: typeof StaffProjectsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/project-sticker': {
      id: '/staff/project-sticker'
      path: '/project-sticker'
      fullPath: '/staff/project-sticker'
      preLoaderRoute: typeof StaffProjectStickerRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/project-qr': {
      id: '/staff/project-qr'
      path: '/project-qr'
      fullPath: '/staff/project-qr'
      preLoaderRoute: typeof StaffProjectQrRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/po-orders': {
      id: '/staff/po-orders'
      path: '/po-orders'
      fullPath: '/staff/po-orders'
      preLoaderRoute: typeof StaffPoOrdersRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/inspections': {
      id: '/staff/inspections'
      path: '/inspections'
      fullPath: '/staff/inspections'
      preLoaderRoute: typeof StaffInspectionsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/inspection-reports': {
      id: '/staff/inspection-reports'
      path: '/inspection-reports'
      fullPath: '/staff/inspection-reports'
      preLoaderRoute: typeof StaffInspectionReportsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/help': {
      id: '/staff/help'
      path: '/help'
      fullPath: '/staff/help'
      preLoaderRoute: typeof StaffHelpRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/growth': {
      id: '/staff/growth'
      path: '/growth'
      fullPath: '/staff/growth'
      preLoaderRoute: typeof StaffGrowthRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/field-work': {
      id: '/staff/field-work'
      path: '/field-work'
      fullPath: '/staff/field-work'
      preLoaderRoute: typeof StaffFieldWorkRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/email': {
      id: '/staff/email'
      path: '/email'
      fullPath: '/staff/email'
      preLoaderRoute: typeof StaffEmailRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/docs': {
      id: '/staff/docs'
      path: '/docs'
      fullPath: '/staff/docs'
      preLoaderRoute: typeof StaffDocsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/crm': {
      id: '/staff/crm'
      path: '/crm'
      fullPath: '/staff/crm'
      preLoaderRoute: typeof StaffCrmRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/consulting-reports': {
      id: '/staff/consulting-reports'
      path: '/consulting-reports'
      fullPath: '/staff/consulting-reports'
      preLoaderRoute: typeof StaffConsultingReportsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/compliance': {
      id: '/staff/compliance'
      path: '/compliance'
      fullPath: '/staff/compliance'
      preLoaderRoute: typeof StaffComplianceRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/clients': {
      id: '/staff/clients'
      path: '/clients'
      fullPath: '/staff/clients'
      preLoaderRoute: typeof StaffClientsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/chat': {
      id: '/staff/chat'
      path: '/chat'
      fullPath: '/staff/chat'
      preLoaderRoute: typeof StaffChatRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/capability': {
      id: '/staff/capability'
      path: '/capability'
      fullPath: '/staff/capability'
      preLoaderRoute: typeof StaffCapabilityRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/billing': {
      id: '/staff/billing'
      path: '/billing'
      fullPath: '/staff/billing'
      preLoaderRoute: typeof StaffBillingRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/automations': {
      id: '/staff/automations'
      path: '/automations'
      fullPath: '/staff/automations'
      preLoaderRoute: typeof StaffAutomationsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/assets-risk': {
      id: '/staff/assets-risk'
      path: '/assets-risk'
      fullPath: '/staff/assets-risk'
      preLoaderRoute: typeof StaffAssetsRiskRouteImport
      parentRoute: typeof StaffRoute
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-scan/$token': {
      id: '/project-scan/$token'
      path: '/project-scan/$token'
      fullPath: '/project-scan/$token'
      preLoaderRoute: typeof ProjectScanTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/vusi-tools/findings-report': {
      id: '/staff/vusi-tools/findings-report'
      path: '/findings-report'
      fullPath: '/staff/vusi-tools/findings-report'
      preLoaderRoute: typeof StaffVusiToolsFindingsReportRouteImport
      parentRoute: typeof StaffVusiToolsRoute
    }
    '/staff/quotes/onsite': {
      id: '/staff/quotes/onsite'
      path: '/onsite'
      fullPath: '/staff/quotes/onsite'
      preLoaderRoute: typeof StaffQuotesOnsiteRouteImport
      parentRoute: typeof StaffQuotesRoute
    }
    '/staff/quotes/new': {
      id: '/staff/quotes/new'
      path: '/new'
      fullPath: '/staff/quotes/new'
      preLoaderRoute: typeof StaffQuotesNewRouteImport
      parentRoute: typeof StaffQuotesRoute
    }
    '/staff/quotes/$quoteId': {
      id: '/staff/quotes/$quoteId'
      path: '/$quoteId'
      fullPath: '/staff/quotes/$quoteId'
      preLoaderRoute: typeof StaffQuotesQuoteIdRouteImport
      parentRoute: typeof StaffQuotesRoute
    }
    '/staff/growth/segments': {
      id: '/staff/growth/segments'
      path: '/segments'
      fullPath: '/staff/growth/segments'
      preLoaderRoute: typeof StaffGrowthSegmentsRouteImport
      parentRoute: typeof StaffGrowthRoute
    }
    '/staff/growth/campaigns': {
      id: '/staff/growth/campaigns'
      path: '/campaigns'
      fullPath: '/staff/growth/campaigns'
      preLoaderRoute: typeof StaffGrowthCampaignsRouteImport
      parentRoute: typeof StaffGrowthRoute
    }
    '/staff/crm/contacts': {
      id: '/staff/crm/contacts'
      path: '/contacts'
      fullPath: '/staff/crm/contacts'
      preLoaderRoute: typeof StaffCrmContactsRouteImport
      parentRoute: typeof StaffCrmRoute
    }
    '/staff/growth/campaigns/$campaignId': {
      id: '/staff/growth/campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/staff/growth/campaigns/$campaignId'
      preLoaderRoute: typeof StaffGrowthCampaignsCampaignIdRouteImport
      parentRoute: typeof StaffGrowthCampaignsRoute
    }
    '/staff/crm/deals/$dealId': {
      id: '/staff/crm/deals/$dealId'
      path: '/deals/$dealId'
      fullPath: '/staff/crm/deals/$dealId'
      preLoaderRoute: typeof StaffCrmDealsDealIdRouteImport
      parentRoute: typeof StaffCrmRoute
    }
    '/staff/crm/contacts/$contactId': {
      id: '/staff/crm/contacts/$contactId'
      path: '/$contactId'
      fullPath: '/staff/crm/contacts/$contactId'
      preLoaderRoute: typeof StaffCrmContactsContactIdRouteImport
      parentRoute: typeof StaffCrmContactsRoute
    }
  }
}

interface StaffCrmContactsRouteChildren {
  StaffCrmContactsContactIdRoute: typeof StaffCrmContactsContactIdRoute
}

const StaffCrmContactsRouteChildren: StaffCrmContactsRouteChildren = {
  StaffCrmContactsContactIdRoute: StaffCrmContactsContactIdRoute,
}

const StaffCrmContactsRouteWithChildren =
  StaffCrmContactsRoute._addFileChildren(StaffCrmContactsRouteChildren)

interface StaffCrmRouteChildren {
  StaffCrmContactsRoute: typeof StaffCrmContactsRouteWithChildren
  StaffCrmDealsDealIdRoute: typeof StaffCrmDealsDealIdRoute
}

const StaffCrmRouteChildren: StaffCrmRouteChildren = {
  StaffCrmContactsRoute: StaffCrmContactsRouteWithChildren,
  StaffCrmDealsDealIdRoute: StaffCrmDealsDealIdRoute,
}

const StaffCrmRouteWithChildren = StaffCrmRoute._addFileChildren(
  StaffCrmRouteChildren,
)

interface StaffGrowthCampaignsRouteChildren {
  StaffGrowthCampaignsCampaignIdRoute: typeof StaffGrowthCampaignsCampaignIdRoute
}

const StaffGrowthCampaignsRouteChildren: StaffGrowthCampaignsRouteChildren = {
  StaffGrowthCampaignsCampaignIdRoute: StaffGrowthCampaignsCampaignIdRoute,
}

const StaffGrowthCampaignsRouteWithChildren =
  StaffGrowthCampaignsRoute._addFileChildren(StaffGrowthCampaignsRouteChildren)

interface StaffGrowthRouteChildren {
  StaffGrowthCampaignsRoute: typeof StaffGrowthCampaignsRouteWithChildren
  StaffGrowthSegmentsRoute: typeof StaffGrowthSegmentsRoute
}

const StaffGrowthRouteChildren: StaffGrowthRouteChildren = {
  StaffGrowthCampaignsRoute: StaffGrowthCampaignsRouteWithChildren,
  StaffGrowthSegmentsRoute: StaffGrowthSegmentsRoute,
}

const StaffGrowthRouteWithChildren = StaffGrowthRoute._addFileChildren(
  StaffGrowthRouteChildren,
)

interface StaffQuotesRouteChildren {
  StaffQuotesQuoteIdRoute: typeof StaffQuotesQuoteIdRoute
  StaffQuotesNewRoute: typeof StaffQuotesNewRoute
  StaffQuotesOnsiteRoute: typeof StaffQuotesOnsiteRoute
}

const StaffQuotesRouteChildren: StaffQuotesRouteChildren = {
  StaffQuotesQuoteIdRoute: StaffQuotesQuoteIdRoute,
  StaffQuotesNewRoute: StaffQuotesNewRoute,
  StaffQuotesOnsiteRoute: StaffQuotesOnsiteRoute,
}

const StaffQuotesRouteWithChildren = StaffQuotesRoute._addFileChildren(
  StaffQuotesRouteChildren,
)

interface StaffVusiToolsRouteChildren {
  StaffVusiToolsFindingsReportRoute: typeof StaffVusiToolsFindingsReportRoute
}

const StaffVusiToolsRouteChildren: StaffVusiToolsRouteChildren = {
  StaffVusiToolsFindingsReportRoute: StaffVusiToolsFindingsReportRoute,
}

const StaffVusiToolsRouteWithChildren = StaffVusiToolsRoute._addFileChildren(
  StaffVusiToolsRouteChildren,
)

interface StaffRouteChildren {
  StaffAssetsRiskRoute: typeof StaffAssetsRiskRoute
  StaffAutomationsRoute: typeof StaffAutomationsRoute
  StaffBillingRoute: typeof StaffBillingRoute
  StaffCapabilityRoute: typeof StaffCapabilityRoute
  StaffChatRoute: typeof StaffChatRoute
  StaffClientsRoute: typeof StaffClientsRoute
  StaffComplianceRoute: typeof StaffComplianceRoute
  StaffConsultingReportsRoute: typeof StaffConsultingReportsRoute
  StaffCrmRoute: typeof StaffCrmRouteWithChildren
  StaffDocsRoute: typeof StaffDocsRoute
  StaffEmailRoute: typeof StaffEmailRoute
  StaffFieldWorkRoute: typeof StaffFieldWorkRoute
  StaffGrowthRoute: typeof StaffGrowthRouteWithChildren
  StaffHelpRoute: typeof StaffHelpRoute
  StaffInspectionReportsRoute: typeof StaffInspectionReportsRoute
  StaffInspectionsRoute: typeof StaffInspectionsRoute
  StaffLoginRoute: typeof StaffLoginRoute
  StaffPoOrdersRoute: typeof StaffPoOrdersRoute
  StaffProjectQrRoute: typeof StaffProjectQrRoute
  StaffProjectStickerRoute: typeof StaffProjectStickerRoute
  StaffProjectsRoute: typeof StaffProjectsRoute
  StaffQuotationsRoute: typeof StaffQuotationsRoute
  StaffQuotesRoute: typeof StaffQuotesRouteWithChildren
  StaffReportsRoute: typeof StaffReportsRoute
  StaffScheduleRoute: typeof StaffScheduleRoute
  StaffSettingsRoute: typeof StaffSettingsRoute
  StaffSiteVisitsRoute: typeof StaffSiteVisitsRoute
  StaffSteveRoute: typeof StaffSteveRoute
  StaffSubcontractorsRoute: typeof StaffSubcontractorsRoute
  StaffVoiceRoute: typeof StaffVoiceRoute
  StaffVusiRoute: typeof StaffVusiRoute
  StaffVusiToolsRoute: typeof StaffVusiToolsRouteWithChildren
  StaffWorkRoute: typeof StaffWorkRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffAssetsRiskRoute: StaffAssetsRiskRoute,
  StaffAutomationsRoute: StaffAutomationsRoute,
  StaffBillingRoute: StaffBillingRoute,
  StaffCapabilityRoute: StaffCapabilityRoute,
  StaffChatRoute: StaffChatRoute,
  StaffClientsRoute: StaffClientsRoute,
  StaffComplianceRoute: StaffComplianceRoute,
  StaffConsultingReportsRoute: StaffConsultingReportsRoute,
  StaffCrmRoute: StaffCrmRouteWithChildren,
  StaffDocsRoute: StaffDocsRoute,
  StaffEmailRoute: StaffEmailRoute,
  StaffFieldWorkRoute: StaffFieldWorkRoute,
  StaffGrowthRoute: StaffGrowthRouteWithChildren,
  StaffHelpRoute: StaffHelpRoute,
  StaffInspectionReportsRoute: StaffInspectionReportsRoute,
  StaffInspectionsRoute: StaffInspectionsRoute,
  StaffLoginRoute: StaffLoginRoute,
  StaffPoOrdersRoute: StaffPoOrdersRoute,
  StaffProjectQrRoute: StaffProjectQrRoute,
  StaffProjectStickerRoute: StaffProjectStickerRoute,
  StaffProjectsRoute: StaffProjectsRoute,
  StaffQuotationsRoute: StaffQuotationsRoute,
  StaffQuotesRoute: StaffQuotesRouteWithChildren,
  StaffReportsRoute: StaffReportsRoute,
  StaffScheduleRoute: StaffScheduleRoute,
  StaffSettingsRoute: StaffSettingsRoute,
  StaffSiteVisitsRoute: StaffSiteVisitsRoute,
  StaffSteveRoute: StaffSteveRoute,
  StaffSubcontractorsRoute: StaffSubcontractorsRoute,
  StaffVoiceRoute: StaffVoiceRoute,
  StaffVusiRoute: StaffVusiRoute,
  StaffVusiToolsRoute: StaffVusiToolsRouteWithChildren,
  StaffWorkRoute: StaffWorkRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  PartnerReferralRoute: PartnerReferralRoute,
  ServicesRoute: ServicesRoute,
  StaffRoute: StaffRouteWithChildren,
  ProjectScanTokenRoute: ProjectScanTokenRoute,
  SignTokenRoute: SignTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
